package org.firstinspires.ftc.teamcode;

public class WORLDSCONSTANTS {

    // Power
    public double SLIDE_UP_POWER, SLIDE_DOWN_POWER, SLIDE_FEEDFORWARD, LINKAGE_COEF, INTAKE_CLAW_SHIFT_COEF;
    public double ARM_TRANSFER_POS, INTAKE_VERT_SHIFT_POS_S;
    // Positions

    public double
            ROTATE_ARM_INTAKE_POS, ROTATE_ARM_OUTTAKE_POS, ROTATE_ARM_TRANSFER_POS, ROTATE_ARM_BUCKET_POS, ROTATE_ARM_SHIFT,
            ROTATE_CLAW_INTAKE_POS, ROTATE_CLAW_OUTTAKE_POS,
            OUTTAKE_CLAW_OPEN_POS, OUTTAKE_CLAW_CLOSE_POS
            ,INTAKE_HOR_SHIFT_POS_SUB, INTAKE_HOR_SHIFT_POS_TRANSFER, INTAKE_HOR_SHIFT_POS_HP, INTAKE_HOR_AUTO_POS
            ,INTAKE_VERT_SHIFT_POS_UP, INTAKE_VERT_SHIFT_POS_DOWN, INTAKE_VERT_SHIFT_POS_TRANSFER, INTAKE_VERT_SHIFT_POS_HP, INTAKE_VERT_AUTO_POS
            ,INTAKE_WRIST_TRANSFER, INTAKE_WRIST_HP, INTAKE_WRIST_AUTO_POS
            ,INTAKE_CLAW_OPEN_POS, INTAKE_CLAW_CLOSE_POS, INTAKE_CLAW_AUTO_POS
            ,SLIDES_SLAM_UP_POS, SLIDES_SLAM_DOWN_POS, SLIDES_SLAM_UP_SAMPLE_POS, SLIDES_SLAM_DOWN_SAMPLE_POS
            ,SLIDES_VERT_MAX_POS, SLIDES_HOR_MAX_POS, SLIDES_HOR_RETRACT_MIN;
    public WORLDSCONSTANTS() {

        //TODO: Positions


        this.ROTATE_ARM_INTAKE_POS = 1;
        this.ROTATE_ARM_OUTTAKE_POS = 0.1;
        this.ROTATE_ARM_TRANSFER_POS = 0;
        this.ROTATE_ARM_BUCKET_POS = 0.8;

        this.ROTATE_ARM_SHIFT = 0.2;


        this.ROTATE_CLAW_INTAKE_POS = 0.05;
        this.ROTATE_CLAW_OUTTAKE_POS = 0.62;

        this.OUTTAKE_CLAW_OPEN_POS = 0.8;
        this.OUTTAKE_CLAW_CLOSE_POS = 1;

        this.INTAKE_HOR_SHIFT_POS_SUB = 0.625;
        this.INTAKE_HOR_SHIFT_POS_TRANSFER = 0.35;
        this.INTAKE_HOR_SHIFT_POS_HP = 0;


        this.INTAKE_VERT_SHIFT_POS_UP = 0.9;
        this.INTAKE_VERT_SHIFT_POS_DOWN = 1;
        this.INTAKE_VERT_SHIFT_POS_HP = 0.8;
        this.INTAKE_VERT_SHIFT_POS_TRANSFER = 0.01;

        this.INTAKE_WRIST_TRANSFER = 0.15;
        this.INTAKE_WRIST_HP = 0.24;

        this.INTAKE_CLAW_CLOSE_POS = 0.8;
        this.INTAKE_CLAW_OPEN_POS = 1;

        //TODO: Encoder Positions

        this.SLIDES_SLAM_UP_POS = 900;
        this.SLIDES_SLAM_DOWN_POS = 0;
        this.SLIDES_SLAM_UP_SAMPLE_POS = 2700;
        this.SLIDES_SLAM_DOWN_SAMPLE_POS = 0;

        this.SLIDES_VERT_MAX_POS = 2775;
        this.SLIDES_HOR_MAX_POS = 188;
        this.SLIDES_HOR_RETRACT_MIN = 85;

        //TODO: Power

        this.SLIDE_UP_POWER = 1;
        this.SLIDE_DOWN_POWER = -1;
        this.SLIDE_FEEDFORWARD = 0.075;

        this.LINKAGE_COEF = -0.75;

        this.INTAKE_CLAW_SHIFT_COEF = 0.2;

        //TODO: Specfically Auto

        this.INTAKE_CLAW_AUTO_POS = 1;
        this.INTAKE_HOR_AUTO_POS = 0.1;
        this.INTAKE_VERT_AUTO_POS = 1;
        this.INTAKE_WRIST_AUTO_POS = 0.3;

    }
}
